#!/usr/bin/env python3
"""Render the dca-bootstrap rule catalog reference from both rule libraries' catalogs.

Reads ``../dca-java/rules.json`` (dca-archunit, the rule ids' source of truth) and
``../dca-dotnet/rules.json`` (DomainCentric.ArchRules: ported rules, ``n/a`` entries with a
reason, and the .NET-only ``DCA-NET`` set), both relative to the marketplace root, and writes
``plugins/dca-core/skills/dca-bootstrap/reference/archunit-rule-catalog.md``. Stdlib only.

Usage:  python3 scripts/render-rule-catalog.py [--java PATH] [--dotnet PATH] [--out PATH]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

MARKETPLACE = Path(__file__).resolve().parent.parent
DEFAULT_JAVA = MARKETPLACE.parent / "dca-java" / "rules.json"
DEFAULT_DOTNET = MARKETPLACE.parent / "dca-dotnet" / "rules.json"
DEFAULT_OUT = (
    MARKETPLACE / "plugins" / "dca-core" / "skills" / "dca-bootstrap" / "reference"
    / "archunit-rule-catalog.md"
)

SET_TITLES = {
    "cycles": "Cyclic dependencies",
    "layered": "Layered Architecture",
    "onion": "Onion Architecture",
    "hexagonal": "Hexagonal Architecture (Ports and Adapters)",
    "naming": "Naming conventions",
    "tactical": "DDD tactical patterns",
    "strategic": "DDD strategic patterns",
    "contextmap": "Context map",
    "advanced": "DDD advanced patterns",
    "usecase": "Use case patterns",
    "dotnet": ".NET-only rules",
}


def cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def render(java: list[dict], dotnet: list[dict]) -> str:
    dotnet_by_id = {r["id"]: r for r in dotnet}
    java_by_id = {r["id"]: r for r in java}
    sets: list[str] = []
    for r in java:
        if r["set"] not in sets:
            sets.append(r["set"])
    for r in dotnet:
        if r["set"] not in sets:
            sets.append(r["set"])

    lines = [
        "# DCA Rule Catalog",
        "",
        "Generated by scripts/render-rule-catalog.py — do not edit.",
        "",
        "Every rule of the two rule libraries `/dca-bootstrap` wires into a project, grouped by rule set."
        " The set name is the value used in `dca.rules.sets` (`dca-archunit.properties`); the id is what"
        " `dca.rules.off`, `dca.rules.warn` and `dca.rule.<id>.reason` refer to.",
        "",
        "| Column | Meaning |",
        "|---|---|",
        "| Java | `dev.domaincentric:dca-archunit` implements the rule |",
        "| .NET | `DomainCentric.ArchRules` implements the rule; *n/a* names why it has no .NET reading |",
        "",
    ]
    java_total = len(java)
    dotnet_total = sum(1 for r in dotnet if r.get("status") != "n/a")
    na_total = sum(1 for r in dotnet if r.get("status") == "n/a")
    lines += [
        f"Java: {java_total} rules in {len({r['set'] for r in java})} sets. .NET: {dotnet_total} rules"
        f" ({dotnet_total - sum(1 for r in dotnet if r['set'] == 'dotnet')} ported +"
        f" {sum(1 for r in dotnet if r['set'] == 'dotnet')} .NET-only), {na_total} Java rules n/a.",
        "",
    ]

    for set_name in sets:
        rows = [r for r in java if r["set"] == set_name] or [r for r in dotnet if r["set"] == set_name]
        lines += [
            f"## `{set_name}` — {SET_TITLES.get(set_name, set_name)}",
            "",
            "| Id | Rule | Rationale | Java | .NET |",
            "|---|---|---|---|---|",
        ]
        for r in rows:
            rid = r["id"]
            in_java = rid in java_by_id
            d = dotnet_by_id.get(rid)
            if d is None:
                net = "—"
            elif d.get("status") == "n/a":
                net = f"n/a — {cell(d.get('reason', ''))}"
            else:
                net = "✓"
            title = cell(r.get("title") or (d or {}).get("title", ""))
            rationale = cell(r.get("rationale") or (d or {}).get("rationale", ""))
            lines.append(
                f"| `{rid}` | {title} | {rationale} | {'✓' if in_java else '—'} | {net} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--java", type=Path, default=DEFAULT_JAVA)
    parser.add_argument("--dotnet", type=Path, default=DEFAULT_DOTNET)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()
    java = json.loads(args.java.read_text(encoding="utf-8"))
    dotnet = json.loads(args.dotnet.read_text(encoding="utf-8"))
    args.out.write_text(render(java, dotnet), encoding="utf-8")
    print(f"{args.out}: {len(java)} Java rules, {len(dotnet)} .NET entries")


if __name__ == "__main__":
    main()
